#ifndef _CALLS_H
#define _CALLS_H 1

#define MAX_CALLS 380
#define CALL(i) (STRCALLS[i])

const char* STRCALLS[] = {
	"sys_restart_syscall",
	"sys_exit",
	"sys_fork",
	"sys_read",
	"sys_write",
	"sys_open",
	"sys_close",
	"sys_ni_syscall",		/* was sys_waitpid */
	"sys_creat",
	"sys_link",
	"sys_unlink",
	"sys_execve",
	"sys_chdir",
	"sys_time",	/* used by libc4 */
	"sys_mknod",
	"sys_chmod",
	"sys_lchown16",
	"sys_ni_syscall",		/* was sys_break */
	"sys_ni_syscall",		/* was sys_stat */
	"sys_lseek",
	"sys_getpid",
	"sys_mount",
	"sys_oldumount",	/* used by libc4 */
	"sys_setuid16",
	"sys_getuid16",
	"sys_stime",
	"sys_ptrace",
	"sys_alarm",	/* used by libc4 */
	"sys_ni_syscall",		/* was sys_fstat */
	"sys_pause",
	"sys_utime",	/* used by libc4 */
	"sys_ni_syscall",		/* was sys_stty */
	"sys_ni_syscall",		/* was sys_getty */
	"sys_access",
	"sys_nice",
	"sys_ni_syscall",		/* was sys_ftime */
	"sys_sync",
	"sys_kill",
	"sys_rename",
	"sys_mkdir",
	"sys_rmdir",
	"sys_dup",
	"sys_pipe",
	"sys_times",
	"sys_ni_syscall",		/* was sys_prof */
	"sys_brk",
	"sys_setgid16",
	"sys_getgid16",
	"sys_ni_syscall",		/* was sys_signal */
	"sys_geteuid16",
	"sys_getegid16",
	"sys_acct",
	"sys_umount",
	"sys_ni_syscall",		/* was sys_lock */
	"sys_ioctl",
	"sys_fcntl",
	"sys_ni_syscall",		/* was sys_mpx */
	"sys_setpgid",
	"sys_ni_syscall",		/* was sys_ulimit */
	"sys_ni_syscall",		/* was sys_olduname */
	"sys_umask",
	"sys_chroot",
	"sys_ustat",
	"sys_dup2",
	"sys_getppid",
	"sys_getpgrp",
	"sys_setsid",
	"sys_sigaction",
	"sys_ni_syscall",		/* was sys_sgetmask */
	"sys_ni_syscall",		/* was sys_ssetmask */
	"sys_setreuid16",
	"sys_setregid16",
	"sys_sigsuspend",
	"sys_sigpending",
	"sys_sethostname",
	"sys_setrlimit",
	"sys_old_getrlimit", /* used by libc4 */
	"sys_getrusage",
	"sys_gettimeofday",
	"sys_settimeofday",
	"sys_getgroups16",
	"sys_setgroups16",
	"sys_old_select",	/* used by libc4 */
	"sys_symlink",
	"sys_ni_syscall",		/* was sys_lstat */
	"sys_readlink",
	"sys_uselib",
	"sys_swapon",
	"sys_reboot",
	"sys_old_readdir",	/* used by libc4 */
	"sys_old_mmap",	/* used by libc4 */
	"sys_munmap",
	"sys_truncate",
	"sys_ftruncate",
	"sys_fchmod",
	"sys_fchown16",
	"sys_getpriority",
	"sys_setpriority",
	"sys_ni_syscall",		/* was sys_profil */
	"sys_statfs",
	"sys_fstatfs",
	"sys_ni_syscall",		/* sys_ioperm */
	"sys_socketcall",
	"sys_syslog",
	"sys_setitimer",
	"sys_getitimer",
	"sys_newstat",
	"sys_newlstat",
	"sys_newfstat",
	"sys_ni_syscall",		/* was sys_uname */
	"sys_ni_syscall",		/* was sys_iopl */
	"sys_vhangup",
	"sys_ni_syscall",
	"sys_syscall",	/* call a syscall */
	"sys_wait4",
	"sys_swapoff",
	"sys_sysinfo",
	"sys_ipc",
	"sys_fsync",
	"sys_sigreturn_wrapper",
	"sys_clone",
	"sys_setdomainname",
	"sys_newuname",
	"sys_ni_syscall",		/* modify_ldt */
	"sys_adjtimex",
	"sys_mprotect",
	"sys_sigprocmask",
	"sys_ni_syscall",		/* was sys_create_module */
	"sys_init_module",
	"sys_delete_module",
	"sys_ni_syscall",		/* was sys_get_kernel_syms */
	"sys_quotactl",
	"sys_getpgid",
	"sys_fchdir",
	"sys_bdflush",
	"sys_sysfs",
	"sys_personality",
	"sys_ni_syscall",		/* reserved for afs_syscall */
	"sys_setfsuid16",
	"sys_setfsgid16",
	"sys_llseek",
	"sys_getdents",
	"sys_select",
	"sys_flock",
	"sys_msync",
	"sys_readv",
	"sys_writev",
	"sys_getsid",
	"sys_fdatasync",
	"sys_sysctl",
	"sys_mlock",
	"sys_munlock",
	"sys_mlockall",
	"sys_munlockall",
	"sys_sched_setparam",
	"sys_sched_getparam",
	"sys_sched_setscheduler",
	"sys_sched_getscheduler",
	"sys_sched_yield",
	"sys_sched_get_priority_max",
	"sys_sched_get_priority_min",
	"sys_sched_rr_get_interval",
	"sys_nanosleep",
	"sys_mremap",
	"sys_setresuid16",
	"sys_getresuid16",
	"sys_ni_syscall",		/* vm86 */
	"sys_ni_syscall",		/* was sys_query_module */
	"sys_poll",
	"sys_ni_syscall",		/* was nfsservctl */
	"sys_setresgid16",
	"sys_getresgid16",
	"sys_prctl",
	"sys_rt_sigreturn_wrapper",
	"sys_rt_sigaction",
	"sys_rt_sigprocmask",
	"sys_rt_sigpending",
	"sys_rt_sigtimedwait",
	"sys_rt_sigqueueinfo",
	"sys_rt_sigsuspend",
	"sys_pread64",
	"sys_pwrite64",
	"sys_chown16",
	"sys_getcwd",
	"sys_capget",
	"sys_capset",
	"sys_sigaltstack",
	"sys_sendfile",
	"sys_ni_syscall",		/* getpmsg */
	"sys_ni_syscall",		/* putpmsg */
	"sys_vfork",
	"sys_getrlimit",
	"sys_mmap2",
	"sys_truncate64",
	"sys_ftruncate64",
	"sys_stat64",
	"sys_lstat64",
	"sys_fstat64",
	"sys_lchown",
	"sys_getuid",
	"sys_getgid",
	"sys_geteuid",
	"sys_getegid",
	"sys_setreuid",
	"sys_setregid",
	"sys_getgroups",
	"sys_setgroups",
	"sys_fchown",
	"sys_setresuid",
	"sys_getresuid",
	"sys_setresgid",
	"sys_getresgid",
	"sys_chown",
	"sys_setuid",
	"sys_setgid",
	"sys_setfsuid",
	"sys_setfsgid",
	"sys_getdents64",
	"sys_pivot_root",
	"sys_mincore",
	"sys_madvise",
	"sys_fcntl64",
	"sys_ni_syscall", /* TUX */
	"sys_ni_syscall",
	"sys_gettid",
	"sys_readahead",
	"sys_setxattr",
	"sys_lsetxattr",
	"sys_fsetxattr",
	"sys_getxattr",
	"sys_lgetxattr",
	"sys_fgetxattr",
	"sys_listxattr",
	"sys_llistxattr",
	"sys_flistxattr",
	"sys_removexattr",
	"sys_lremovexattr",
	"sys_fremovexattr",
	"sys_tkill",
	"sys_sendfile64",
	"sys_futex",
	"sys_sched_setaffinity",
	"sys_sched_getaffinity",
	"sys_io_setup",
	"sys_io_destroy",
	"sys_io_getevents",
	"sys_io_submit",
	"sys_io_cancel",
	"sys_exit_group",
	"sys_lookup_dcookie",
	"sys_epoll_create",
	"sys_epoll_ctl",
	"sys_epoll_wait",
	"sys_remap_file_pages",
	"sys_ni_syscall",	/* sys_set_thread_area */
	"sys_ni_syscall",	/* sys_get_thread_area */
	"sys_set_tid_address",
	"sys_timer_create",
	"sys_timer_settime",
	"sys_timer_gettime",
	"sys_timer_getoverrun",
	"sys_timer_delete",
	"sys_clock_settime",
	"sys_clock_gettime",
	"sys_clock_getres",
	"sys_clock_nanosleep",
	"sys_statfs64_wrapper",
	"sys_fstatfs64_wrapper",
	"sys_tgkill",
	"sys_utimes",
	"sys_arm_fadvise64_64",
	"sys_pciconfig_iobase",
	"sys_pciconfig_read",
	"sys_pciconfig_write",
	"sys_mq_open",
	"sys_mq_unlink",
	"sys_mq_timedsend",
	"sys_mq_timedreceive",
	"sys_mq_notify",
	"sys_mq_getsetattr",
	"sys_waitid",
	"sys_socket",
	"sys_bind",
	"sys_connect",
	"sys_listen",
	"sys_accept",
	"sys_getsockname",
	"sys_getpeername",
	"sys_socketpair",
	"sys_send",
	"sys_sendto",
	"sys_recv",
	"sys_recvfrom",
	"sys_shutdown",
	"sys_setsockopt",
	"sys_getsockopt",
	"sys_sendmsg",
	"sys_recvmsg",
	"sys_semop",
	"sys_semget",
	"sys_semctl",
	"sys_msgsnd",
	"sys_msgrcv",
	"sys_msgget",
	"sys_msgctl",
	"sys_shmat",
	"sys_shmdt",
	"sys_shmget",
	"sys_shmctl",
	"sys_add_key",
	"sys_request_key",
	"sys_keyctl",
	"sys_semtimedop",
	"sys_ni_syscall",
	"sys_ioprio_set",
	"sys_ioprio_get",
	"sys_inotify_init",
	"sys_inotify_add_watch",
	"sys_inotify_rm_watch",
	"sys_mbind",
	"sys_get_mempolicy",
	"sys_set_mempolicy",
	"sys_openat",
	"sys_mkdirat",
	"sys_mknodat",
	"sys_fchownat",
	"sys_futimesat",
	"sys_fstatat64",
	"sys_unlinkat",
	"sys_renameat",
	"sys_linkat",
	"sys_symlinkat",
	"sys_readlinkat",
	"sys_fchmodat",
	"sys_faccessat",
	"sys_pselect6",
	"sys_ppoll",
	"sys_unshare",
	"sys_set_robust_list",
	"sys_get_robust_list",
	"sys_splice",
	"sys_sync_file_range2",
	"sys_tee",
	"sys_vmsplice",
	"sys_move_pages",
	"sys_getcpu",
	"sys_epoll_pwait",
	"sys_kexec_load",
	"sys_utimensat",
	"sys_signalfd",
	"sys_timerfd_create",
	"sys_eventfd",
	"sys_fallocate",
	"sys_timerfd_settime",
	"sys_timerfd_gettime",
	"sys_signalfd4",
	"sys_eventfd2",
	"sys_epoll_create1",
	"sys_dup3",
	"sys_pipe2",
	"sys_inotify_init1",
	"sys_preadv",
	"sys_pwritev",
	"sys_rt_tgsigqueueinfo",
	"sys_perf_event_open",
	"sys_recvmmsg",
	"sys_accept4",
	"sys_fanotify_init",
	"sys_fanotify_mark",
	"sys_prlimit64",
	"sys_name_to_handle_at",
	"sys_open_by_handle_at",
	"sys_clock_adjtime",
	"sys_syncfs",
	"sys_sendmmsg",
	"sys_setns",
	"sys_process_vm_readv",
	"sys_process_vm_writev",
	"sys_kcmp",
	"sys_finit_module"
};

#endif /* _CALLS_H */

